services:
  api:
    build:
      context: .
    command: bash -c "python src/ml/train.py && uvicorn 'src.api.app:app' --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    environment:
      - MODEL_NAME=Production-model
      - GIT_PYTHON_REFRESH=quiet
  ui:
    build:
      context: .
    command: streamlit run src/ui/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
