name: Python CI with Poetry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # -----------------------
  # 1) Job de tests Python
  # -----------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version
      
      - name: Install dependencies
        run: poetry install --no-root
      
      - name: Build model
        run: poetry run python src/ml/train.py

      - name: Run tests
        run: poetry run pytest

  # -------------------------------
  # 2) Job de test Docker (parallèle)
  # -------------------------------
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check Docker versions
        run: |
          docker --version
          docker-compose --version

      - name: Build and run Docker containers
        run: |
          # Construction des images via docker-compose
          docker-compose build
          
          # Lancement des services en détaché
          docker-compose up -d
